var srcIndex = new Map(JSON.parse('[\
["bitflags",["",[],["external.rs","internal.rs","iter.rs","lib.rs","parser.rs","public.rs","traits.rs"]]],\
["cfg_if",["",[],["lib.rs"]]],\
["dlib",["",[],["lib.rs"]]],\
["downcast_rs",["",[],["lib.rs"]]],\
["equivalent",["",[],["lib.rs"]]],\
["fastrand",["",[],["global_rng.rs","lib.rs"]]],\
["fixedbitset",["",[],["lib.rs","range.rs"]]],\
["fnv",["",[],["lib.rs"]]],\
["hashbrown",["",[["external_trait_impls",[],["mod.rs"]],["raw",[],["alloc.rs","bitmask.rs","mod.rs","sse2.rs"]]],["lib.rs","macros.rs","map.rs","scopeguard.rs","set.rs","table.rs"]]],\
["home",["",[],["env.rs","lib.rs"]]],\
["indexmap",["",[["map",[["core",[],["entry.rs","raw_entry_v1.rs"]]],["core.rs","iter.rs","mutable.rs","slice.rs"]],["set",[],["iter.rs","mutable.rs","slice.rs"]]],["arbitrary.rs","lib.rs","macros.rs","map.rs","set.rs","util.rs"]]],\
["libc",["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]]],\
["libloading",["",[["os",[["unix",[],["consts.rs","mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]]],\
["linux_raw_sys",["",[["x86_64",[],["errno.rs","general.rs","if_ether.rs","ioctl.rs","net.rs","netlink.rs","prctl.rs","xdp.rs"]]],["elf.rs","lib.rs"]]],\
["log",["",[],["__private_api.rs","lib.rs","macros.rs"]]],\
["memchr",["",[["arch",[["all",[["packedpair",[],["default_rank.rs","mod.rs"]]],["memchr.rs","mod.rs","rabinkarp.rs","shiftor.rs","twoway.rs"]],["generic",[],["memchr.rs","mod.rs","packedpair.rs"]],["x86_64",[["avx2",[],["memchr.rs","mod.rs","packedpair.rs"]],["sse2",[],["memchr.rs","mod.rs","packedpair.rs"]]],["memchr.rs","mod.rs"]]],["mod.rs"]],["memmem",[],["mod.rs","searcher.rs"]]],["cow.rs","ext.rs","lib.rs","macros.rs","memchr.rs","vector.rs"]]],\
["minimal_lexical",["",[],["bigint.rs","extended_float.rs","lemire.rs","lib.rs","mask.rs","num.rs","number.rs","parse.rs","rounding.rs","slow.rs","stackvec.rs","table.rs","table_lemire.rs","table_small.rs"]]],\
["nom",["",[["bits",[],["complete.rs","mod.rs","streaming.rs"]],["branch",[],["mod.rs"]],["bytes",[],["complete.rs","mod.rs","streaming.rs"]],["character",[],["complete.rs","mod.rs","streaming.rs"]],["combinator",[],["mod.rs"]],["multi",[],["mod.rs"]],["number",[],["complete.rs","mod.rs","streaming.rs"]],["sequence",[],["mod.rs"]]],["error.rs","internal.rs","lib.rs","macros.rs","str.rs","traits.rs"]]],\
["once_cell",["",[],["imp_std.rs","lib.rs","race.rs"]]],\
["os_pipe",["",[],["lib.rs","unix.rs"]]],\
["petgraph",["",[["algo",[],["astar.rs","bellman_ford.rs","dijkstra.rs","dominators.rs","feedback_arc_set.rs","floyd_warshall.rs","ford_fulkerson.rs","isomorphism.rs","k_shortest_path.rs","matching.rs","min_spanning_tree.rs","mod.rs","page_rank.rs","simple_paths.rs","tred.rs"]],["graph_impl",[["stable_graph",[],["mod.rs"]]],["frozen.rs","mod.rs"]],["visit",[],["dfsvisit.rs","filter.rs","macros.rs","mod.rs","reversed.rs","traversal.rs"]]],["adj.rs","csr.rs","data.rs","dot.rs","graphmap.rs","iter_format.rs","iter_utils.rs","lib.rs","macros.rs","matrix_graph.rs","operator.rs","prelude.rs","scored.rs","traits_graph.rs","unionfind.rs","util.rs"]]],\
["proc_macro2",["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]]],\
["quick_xml",["",[["events",[],["attributes.rs","mod.rs"]],["parser",[],["element.rs","mod.rs","pi.rs"]],["reader",[],["buffered_reader.rs","mod.rs","ns_reader.rs","slice_reader.rs","state.rs"]]],["encoding.rs","errors.rs","escape.rs","lib.rs","name.rs","utils.rs","writer.rs"]]],\
["quote",["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]]],\
["rustix",["",[["backend",[["linux_raw",[["arch",[],["mod.rs","x86_64.rs"]],["event",[],["epoll.rs","mod.rs","poll_fd.rs","syscalls.rs","types.rs"]],["fs",[],["dir.rs","inotify.rs","makedev.rs","mod.rs","syscalls.rs","types.rs"]],["io",[],["errno.rs","mod.rs","syscalls.rs","types.rs"]],["mount",[],["mod.rs","syscalls.rs","types.rs"]],["net",[],["addr.rs","mod.rs","msghdr.rs","netdevice.rs","read_sockaddr.rs","send_recv.rs","sockopt.rs","syscalls.rs","write_sockaddr.rs"]],["param",[],["libc_auxv.rs","mod.rs"]],["pid",[],["mod.rs","syscalls.rs"]],["prctl",[],["mod.rs","syscalls.rs"]],["process",[],["cpu_set.rs","mod.rs","syscalls.rs","types.rs","wait.rs"]],["ugid",[],["mod.rs","syscalls.rs"]]],["c.rs","conv.rs","mod.rs","reg.rs","vdso.rs","vdso_wrappers.rs"]]]],["event",[],["epoll.rs","eventfd.rs","mod.rs","pause.rs","poll.rs"]],["fs",[],["abs.rs","at.rs","constants.rs","copy_file_range.rs","cwd.rs","dir.rs","fadvise.rs","fcntl.rs","fd.rs","id.rs","inotify.rs","ioctl.rs","makedev.rs","memfd_create.rs","mod.rs","mount.rs","openat2.rs","raw_dir.rs","seek_from.rs","sendfile.rs","statx.rs","sync.rs","xattr.rs"]],["io",[],["close.rs","dup.rs","errno.rs","fcntl.rs","ioctl.rs","is_read_write.rs","mod.rs","read_write.rs"]],["ioctl",[],["linux.rs","mod.rs","patterns.rs"]],["maybe_polyfill",[["std",[],["mod.rs"]]]],["mount",[],["mod.rs","mount_unmount.rs","types.rs"]],["net",[["send_recv",[],["mod.rs","msg.rs"]]],["mod.rs","netdevice.rs","socket.rs","socket_addr_any.rs","socketpair.rs","sockopt.rs","types.rs"]],["path",[],["arg.rs","mod.rs"]],["process",[],["chdir.rs","chroot.rs","exit.rs","id.rs","ioctl.rs","kill.rs","membarrier.rs","mod.rs","pidfd.rs","pidfd_getfd.rs","pivot_root.rs","prctl.rs","priority.rs","rlimit.rs","sched.rs","sched_yield.rs","umask.rs","wait.rs"]]],["bitcast.rs","buffer.rs","cstr.rs","ffi.rs","lib.rs","pid.rs","prctl.rs","signal.rs","timespec.rs","ugid.rs","utils.rs","weak.rs"]]],\
["scoped_tls",["",[],["lib.rs"]]],\
["smallvec",["",[],["lib.rs"]]],\
["syn",["",[["gen",[],["clone.rs"]]],["attr.rs","bigint.rs","buffer.rs","classify.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","fixup.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","meta.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","precedence.rs","print.rs","punctuated.rs","restriction.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]]],\
["tempfile",["",[["dir",[["imp",[],["mod.rs","unix.rs"]]],["mod.rs"]],["file",[["imp",[],["mod.rs","unix.rs"]]],["mod.rs"]]],["env.rs","error.rs","lib.rs","spooled.rs","util.rs"]]],\
["thiserror",["",[],["aserror.rs","display.rs","lib.rs"]]],\
["thiserror_impl",["",[],["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","span.rs","valid.rs"]]],\
["tree_magic_mini",["",[["basetype",[],["check.rs","init.rs","mod.rs"]],["fdo_magic",[["builtin",[],["check.rs","init.rs","mod.rs","runtime.rs"]]],["check.rs","mod.rs","ruleset.rs"]]],["lib.rs"]]],\
["unicode_ident",["",[],["lib.rs","tables.rs"]]],\
["wayland_backend",["",[["rs",[["client_impl",[],["mod.rs"]],["server_impl",[],["client.rs","common_poll.rs","handle.rs","mod.rs","registry.rs"]]],["map.rs","mod.rs","socket.rs","wire.rs"]],["types",[],["client.rs","mod.rs","server.rs"]]],["client_api.rs","core_interfaces.rs","debug.rs","lib.rs","protocol.rs","server_api.rs"]]],\
["wayland_client",["",[],["conn.rs","event_queue.rs","globals.rs","lib.rs"]]],\
["wayland_protocols",["",[],["ext.rs","lib.rs","protocol_macro.rs","wp.rs","xdg.rs","xwayland.rs"]]],\
["wayland_protocols_wlr",["",[],["lib.rs","protocol_macro.rs"]]],\
["wayland_scanner",["",[],["c_interfaces.rs","client_gen.rs","common.rs","interfaces.rs","lib.rs","parse.rs","protocol.rs","server_gen.rs","token.rs","util.rs"]]],\
["wayland_sys",["",[],["client.rs","common.rs","lib.rs","server.rs"]]],\
["wl_clipboard_rs",["",[],["common.rs","copy.rs","lib.rs","paste.rs","seat_data.rs","utils.rs"]]]\
]'));
createSrcSidebar();
